### PR TITLE
Dev utm

### PR DESCRIPTION
**Pull request by Kyle-Fozo**
Please review for merge.  Everything tests out manually, but I have not done automated testing yet.

### CODE REVIEW

**Comment by Kyle-Fozo** [comment]
@alextremblay

**Review by Kyle-Fozo — COMMENTED** [review]
Looks great, thank you for the cleanup, and suggestions to improve this.

**Review by Kyle-Fozo — COMMENTED** [review]
LGTM

**Review by alextremblay — APPROVED** [review]
all code reviewed by both of us

**Pull request merged**
